#!/usr/bin/env bash

#######################################
# Useful script for channels updating #
#######################################

# Getting script directory
# @see https://stackoverflow.com/questions/59895/how-do-i-get-the-directory-where-a-bash-script-is-located-from-within-the-script
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

export SCRIPT_DIR
guix pull --channels=$SCRIPT_DIR/channels.scm
# guix describe --format=channels > ~/.config/guix/channels.scm
